name: ui_mmr
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_datetime_picker: 1.2.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/icon.jpg
     - assets/images/profile.jpg
     - assets/images/rider_1.jpg
     - assets/images/rider_2.jpg
     - assets/images/Bikes/OthunderbirdRxB.jpg
     - assets/images/Bikes/thunderbirdB.jpg
     - assets/images/Bikes/classic_gunmetal_grey.jpg
     - assets/images/Bikes/classic350B.jpg
     - assets/images/Bikes/classic350S.jpg
     - assets/images/Bikes/himalayan_bs4_snow.jpg
     - assets/images/Bikes/himalayan_bs4_ABS.jpg
     - assets/images/Scooty/zestYellow.jpg
     - assets/images/Scooty/ntorqGrey.jpg
     - assets/images/Scooty/ntorqBlue.jpg
     - assets/images/Scooty/apriliaWhite.jpg
     - assets/images/Scooty/apriliaGreen.jpg
     - assets/images/Scooty/apriliaBlack.jpg
    
     
    
  #  - lib/images/images.jpg
  #  - lib/images/images2.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Future
       fonts:
         - asset: fonts/Future.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: OnesilverSignature
       fonts:
         - asset: fonts/OnesilverSignature.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
           weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
